# -*- coding: utf-8 -*-
"""Drug_Side_Effects_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i943ZqcOdtP4sg_xPQqVCn1B1jSvLKz2

# Drug Side Effects - Clasificacion y RAG con Mistral

Proyecto: Algoritmos de clasificacion aplicados a efectos secundarios de medicamentos.

Dataset: 5000 registros de pacientes con reacciones adversas a farmacos.

**Objetivos:**
1. Normalizar el dataset (valores inconsistentes, nulos, formatos mixtos)
2. Entrenar y seleccionar el mejor modelo de clasificacion para predecir severidad
3. Crear un agente RAG con Mistral AI para responder preguntas sobre el dataset

## 1. Instalacion de librerias
"""

!pip install pandas numpy scikit-learn matplotlib seaborn faiss-cpu transformers sentence-transformers langchain langchain-mistralai langchain-community langchain-core -q

"""## 2. Importaciones"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import io
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             confusion_matrix, classification_report, roc_auc_score)
from sklearn.feature_selection import SelectKBest, chi2

from langchain_mistralai import ChatMistralAI, MistralAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.messages import HumanMessage, SystemMessage
import torch

print("Todas las librerias importadas correctamente.")

"""## 3. Configuracion Mistral AI

Modelo recomendado: **mistral-large-latest** (2407) - mejor rendimiento para razonamiento complejo y RAG.
Para embeddings: **mistral-embed**.
"""

from google.colab import userdata
import os
os.environ["MISTRAL_API_KEY"] = userdata.get('Llavekey')

llm = ChatMistralAI(
    model="mistral-large-latest",
    temperature=0,
    api_key=os.environ["MISTRAL_API_KEY"]
)
embeddings = MistralAIEmbeddings(
    model="mistral-embed",
    api_key=os.environ["MISTRAL_API_KEY"]
)

print(f"LLM Mistral configurado: mistral-large-latest, temperature=0")
print(f"Embeddings Mistral configurados: mistral-embed")

"""## 4. Carga del dataset

El archivo debe subirse a Colab con el nombre `drug_side_effects_5000.csv`.
"""

# Cargar con encoding flexible
encodings = ["utf-8", "latin1", "cp1252", "iso-8859-1"]
df = None
for enc in encodings:
    try:
        df = pd.read_csv("drug_side_effects_5000.csv", encoding=enc)
        print(f"Cargado con encoding: {enc}")
        break
    except UnicodeDecodeError:
        continue

print(f"Shape: {df.shape}")
df.head()

"""## 5. Diagnostico inicial"""

print("=== INFO ===")
df.info()
print("\n=== NULLS ===")
print(df.isnull().sum())
print("\n=== DTYPES ===")
print(df.dtypes)
print("\n=== HEAD ===")
df.head()

"""## 6. Normalizacion del dataset

### 6.1 Renombrar columnas a snake_case
"""

col_map = {
    "PatientID": "patient_id",
    " Age ": "age",
    "GENDER": "gender",
    "Country": "country",
    "DrugName": "drug_name",
    "Dosage (mg)": "dosage_mg",
    "sideEffect": "side_effect",
    " Severity ": "severity",
    "Outcome": "outcome",
    "Report Date": "report_date",
    "TreatmentStart": "treatment_start_date",
    "ChronicCondition": "chronic_condition",
    "Smoker": "smoker",
    "Alcohol Use": "alcohol_use",
    "Hospitalized": "hospitalized",
    "Recovery Days": "recovery_days",
}
df.rename(columns=col_map, inplace=True)
print(f"Columnas: {list(df.columns)}")

"""### 6.2 Conversion de tipos numericos"""

# Age: limpiar "years", "yo", espacios
def clean_age(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().lower()
    val = val.replace("years", "").replace("year", "").replace("yo", "").replace("old", "").strip()
    try:
        return int(float(val))
    except:
        return np.nan

df["age"] = df["age"].apply(clean_age)

# Dosage: limpiar "mg"
def clean_dosage(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().lower().replace("mg", "").replace(" ", "")
    try:
        return int(float(val))
    except:
        return np.nan

df["dosage_mg"] = df["dosage_mg"].apply(clean_dosage)

# Recovery days: limpiar "days", "d"
def clean_recovery(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().lower().replace("days", "").replace("day", "").replace("d", "")
    try:
        return float(val)
    except:
        return np.nan

df["recovery_days"] = df["recovery_days"].apply(clean_recovery)

print(f"age: {df['age'].dtype}, min={df['age'].min()}, max={df['age'].max()}")
print(f"dosage_mg: {df['dosage_mg'].dtype}, min={df['dosage_mg'].min()}, max={df['dosage_mg'].max()}")
print(f"recovery_days: {df['recovery_days'].dtype}, min={df['recovery_days'].min()}, max={df['recovery_days'].max()}")

"""### 6.3 Conversion de fechas"""

def parse_date(val):
    if pd.isna(val):
        return pd.NaT
    val = str(val).strip()
    formats = ["%Y-%m-%d", "%d/%m/%Y", "%m-%d-%Y", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"]
    for fmt in formats:
        try:
            return pd.to_datetime(val, format=fmt)
        except:
            continue
    try:
        return pd.to_datetime(val, dayfirst=True)
    except:
        return pd.NaT

df["report_date"] = df["report_date"].apply(parse_date)
df["treatment_start_date"] = df["treatment_start_date"].apply(parse_date)

print(f"report_date: {df['report_date'].dtype}")
print(f"treatment_start_date: {df['treatment_start_date'].dtype}")

"""### 6.4 Limpieza de strings y estandarizacion"""

# Reemplazar strings que representan nulos
null_vals = ["nan", "NaN", "N/A", "NaT", "<NA>", "None", "none", "", "Unknown", "never"]

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace(null_vals, np.nan)
    df[col] = df[col].str.replace(r"\s+", " ", regex=True)

# Gender
def norm_gender(v):
    if pd.isna(v): return np.nan
    v = str(v).strip().lower()
    return {"male": "Male", "m": "Male", "female": "Female", "f": "Female"}.get(v, v)
df["gender"] = df["gender"].apply(norm_gender)

# Country
def norm_country(v):
    if pd.isna(v): return np.nan
    v = str(v).strip().title()
    return {"Usa": "USA", "Us": "USA", "U.S.A": "USA", "Uk": "UK", "U.K": "UK"}.get(v, v)
df["country"] = df["country"].apply(norm_country)

# Severity
def norm_severity(v):
    if pd.isna(v): return np.nan
    return {"mild": "Mild", "moderate": "Moderate", "severe": "Severe"}.get(str(v).strip().lower(), v)
df["severity"] = df["severity"].apply(norm_severity)

# Outcome
def norm_outcome(v):
    if pd.isna(v): return np.nan
    return {"recovered": "Recovered", "recovering": "Recovering",
            "fatal": "Fatal", "hospitalized": "Hospitalized"}.get(str(v).strip().lower(), v)
df["outcome"] = df["outcome"].apply(norm_outcome)

# Smoker
def norm_smoker(v):
    if pd.isna(v): return np.nan
    v = str(v).strip().lower()
    return {"yes": "Yes", "y": "Yes", "no": "No", "n": "No"}.get(v, v)
df["smoker"] = df["smoker"].apply(norm_smoker)

# Hospitalized
def norm_hosp(v):
    if pd.isna(v): return np.nan
    v = str(v).strip().lower()
    return {"yes": "Yes", "true": "Yes", "no": "No", "false": "No"}.get(v, v)
df["hospitalized"] = df["hospitalized"].apply(norm_hosp)

# Title case para drug_name y side_effect
df["drug_name"] = df["drug_name"].str.title().str.strip()
df["side_effect"] = df["side_effect"].str.title().str.strip()
df["chronic_condition"] = df["chronic_condition"].str.title().str.strip()

print("Strings limpiados y estandarizados.")

"""### 6.5 Manejo de nulos"""

print("Nulos antes:")
print(df.isnull().sum())
print()

# Imputar numericos con mediana
df["age"] = df["age"].fillna(df["age"].median()).astype(int)
df["dosage_mg"] = df["dosage_mg"].fillna(df["dosage_mg"].median()).astype(int)
df["recovery_days"] = df["recovery_days"].fillna(df["recovery_days"].median())

# Imputar categoricos con moda
for col in ["chronic_condition", "alcohol_use"]:
    df[col] = df[col].fillna(df[col].mode()[0])

# Eliminar filas con fechas nulas
df.dropna(subset=["report_date", "treatment_start_date"], inplace=True)
df.reset_index(drop=True, inplace=True)

print("Nulos despues:")
print(df.isnull().sum())
print(f"\nShape final: {df.shape}")

"""## 7. Analisis Exploratorio (EDA)"""

# Distribucion de severidad (target)
print("Distribucion de severidad:")
print(df["severity"].value_counts())
print()
print("Distribucion de outcome:")
print(df["outcome"].value_counts())
print()
print("Distribucion de hospitalized:")
print(df["hospitalized"].value_counts())

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
df["severity"].value_counts().plot(kind="bar", ax=axes[0], title="Severidad")
df["outcome"].value_counts().plot(kind="bar", ax=axes[1], title="Outcome")
df["hospitalized"].value_counts().plot(kind="bar", ax=axes[2], title="Hospitalizado")
plt.tight_layout()
plt.show()

# Distribucion de edad por severidad
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
sns.boxplot(x="severity", y="age", data=df)
plt.title("Edad por severidad")
plt.subplot(1, 2, 2)
sns.boxplot(x="severity", y="dosage_mg", data=df)
plt.title("Dosis por severidad")
plt.tight_layout()
plt.show()

# Variables categoricas vs severidad
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
cat_cols = ["gender", "smoker", "chronic_condition", "alcohol_use", "country", "drug_name"]
for ax, col in zip(axes.flatten(), cat_cols):
    crosstab = pd.crosstab(df[col], df["severity"], normalize="index")
    crosstab.plot(kind="bar", stacked=True, ax=ax, legend=False)
    ax.set_title(f"Severidad por {col}")
    ax.tick_params(axis="x", rotation=45)
plt.tight_layout()
plt.show()
