# -*- coding: utf-8 -*-
"""Drug_Side_Effects_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i943ZqcOdtP4sg_xPQqVCn1B1jSvLKz2

# Drug Side Effects - Clasificacion y RAG con Mistral

Proyecto: Algoritmos de clasificacion aplicados a efectos secundarios de medicamentos.

Dataset: 5000 registros de pacientes con reacciones adversas a farmacos.

**Objetivos:**
1. Normalizar el dataset (valores inconsistentes, nulos, formatos mixtos)
2. Entrenar y seleccionar el mejor modelo de clasificacion para predecir severidad
3. Crear un agente RAG con Mistral AI para responder preguntas sobre el dataset

## 1. Instalacion de librerias
"""

!pip install pandas numpy scikit-learn matplotlib seaborn faiss-cpu transformers sentence-transformers langchain langchain-mistralai langchain-community langchain-core -q

"""## 2. Importaciones"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import io
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             confusion_matrix, classification_report, roc_auc_score)
from sklearn.feature_selection import SelectKBest, chi2

from langchain_mistralai import ChatMistralAI, MistralAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.messages import HumanMessage, SystemMessage
import torch

print("Todas las librerias importadas correctamente.")

"""## 3. Configuracion Mistral AI

Modelo recomendado: **mistral-large-latest** (2407) - mejor rendimiento para razonamiento complejo y RAG.
Para embeddings: **mistral-embed**.
"""

from google.colab import userdata
import os
os.environ["MISTRAL_API_KEY"] = userdata.get('Llavekey')

llm = ChatMistralAI(
    model="mistral-large-latest",
    temperature=0,
    api_key=os.environ["MISTRAL_API_KEY"]
)
embeddings = MistralAIEmbeddings(
    model="mistral-embed",
    api_key=os.environ["MISTRAL_API_KEY"]
)

print(f"LLM Mistral configurado: mistral-large-latest, temperature=0")
print(f"Embeddings Mistral configurados: mistral-embed")

"""## 4. Carga del dataset

El archivo debe subirse a Colab con el nombre `drug_side_effects_5000.csv`.
"""

# Cargar con encoding flexible
encodings = ["utf-8", "latin1", "cp1252", "iso-8859-1"]
df = None
for enc in encodings:
    try:
        df = pd.read_csv("drug_side_effects_5000.csv", encoding=enc)
        print(f"Cargado con encoding: {enc}")
        break
    except UnicodeDecodeError:
        continue

print(f"Shape: {df.shape}")
df.head()

"""## 5. Diagnostico inicial"""

print("=== INFO ===")
df.info()
print("\n=== NULLS ===")
print(df.isnull().sum())
print("\n=== DTYPES ===")
print(df.dtypes)
print("\n=== HEAD ===")
df.head()

"""## 6. Normalizacion del dataset

### 6.1 Renombrar columnas a snake_case
"""

col_map = {
    "PatientID": "patient_id",
    " Age ": "age",
    "GENDER": "gender",
    "Country": "country",
    "DrugName": "drug_name",
    "Dosage (mg)": "dosage_mg",
    "sideEffect": "side_effect",
    " Severity ": "severity",
    "Outcome": "outcome",
    "Report Date": "report_date",
    "TreatmentStart": "treatment_start_date",
    "ChronicCondition": "chronic_condition",
    "Smoker": "smoker",
    "Alcohol Use": "alcohol_use",
    "Hospitalized": "hospitalized",
    "Recovery Days": "recovery_days",
}
df.rename(columns=col_map, inplace=True)
print(f"Columnas: {list(df.columns)}")

"""### 6.2 Conversion de tipos numericos"""

# Age: limpiar "years", "yo", espacios
def clean_age(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().lower()
    val = val.replace("years", "").replace("year", "").replace("yo", "").replace("old", "").strip()
    try:
        return int(float(val))
    except:
        return np.nan

df["age"] = df["age"].apply(clean_age)

# Dosage: limpiar "mg"
def clean_dosage(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().lower().replace("mg", "").replace(" ", "")
    try:
        return int(float(val))
    except:
        return np.nan

df["dosage_mg"] = df["dosage_mg"].apply(clean_dosage)

# Recovery days: limpiar "days", "d"
def clean_recovery(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().lower().replace("days", "").replace("day", "").replace("d", "")
    try:
        return float(val)
    except:
        return np.nan

df["recovery_days"] = df["recovery_days"].apply(clean_recovery)

print(f"age: {df['age'].dtype}, min={df['age'].min()}, max={df['age'].max()}")
print(f"dosage_mg: {df['dosage_mg'].dtype}, min={df['dosage_mg'].min()}, max={df['dosage_mg'].max()}")
print(f"recovery_days: {df['recovery_days'].dtype}, min={df['recovery_days'].min()}, max={df['recovery_days'].max()}")

"""### 6.3 Conversion de fechas"""

def parse_date(val):
    if pd.isna(val):
        return pd.NaT
    val = str(val).strip()
    formats = ["%Y-%m-%d", "%d/%m/%Y", "%m-%d-%Y", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"]
    for fmt in formats:
        try:
            return pd.to_datetime(val, format=fmt)
        except:
            continue
    try:
        return pd.to_datetime(val, dayfirst=True)
    except:
        return pd.NaT

df["report_date"] = df["report_date"].apply(parse_date)
df["treatment_start_date"] = df["treatment_start_date"].apply(parse_date)

print(f"report_date: {df['report_date'].dtype}")
print(f"treatment_start_date: {df['treatment_start_date'].dtype}")

"""### 6.4 Limpieza de strings y estandarizacion"""

# Reemplazar strings que representan nulos
null_vals = ["nan", "NaN", "N/A", "NaT", "<NA>", "None", "none", "", "Unknown", "never"]

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace(null_vals, np.nan)
    df[col] = df[col].str.replace(r"\s+", " ", regex=True)

# Gender
def norm_gender(v):
    if pd.isna(v): return np.nan
    v = str(v).strip().lower()
    return {"male": "Male", "m": "Male", "female": "Female", "f": "Female"}.get(v, v)
df["gender"] = df["gender"].apply(norm_gender)

# Country
def norm_country(v):
    if pd.isna(v): return np.nan
    v = str(v).strip().title()
    return {"Usa": "USA", "Us": "USA", "U.S.A": "USA", "Uk": "UK", "U.K": "UK"}.get(v, v)
df["country"] = df["country"].apply(norm_country)

# Severity
def norm_severity(v):
    if pd.isna(v): return np.nan
    return {"mild": "Mild", "moderate": "Moderate", "severe": "Severe"}.get(str(v).strip().lower(), v)
df["severity"] = df["severity"].apply(norm_severity)

# Outcome
def norm_outcome(v):
    if pd.isna(v): return np.nan
    return {"recovered": "Recovered", "recovering": "Recovering",
            "fatal": "Fatal", "hospitalized": "Hospitalized"}.get(str(v).strip().lower(), v)
df["outcome"] = df["outcome"].apply(norm_outcome)

# Smoker
def norm_smoker(v):
    if pd.isna(v): return np.nan
    v = str(v).strip().lower()
    return {"yes": "Yes", "y": "Yes", "no": "No", "n": "No"}.get(v, v)
df["smoker"] = df["smoker"].apply(norm_smoker)

# Hospitalized
def norm_hosp(v):
    if pd.isna(v): return np.nan
    v = str(v).strip().lower()
    return {"yes": "Yes", "true": "Yes", "no": "No", "false": "No"}.get(v, v)
df["hospitalized"] = df["hospitalized"].apply(norm_hosp)

# Title case para drug_name y side_effect
df["drug_name"] = df["drug_name"].str.title().str.strip()
df["side_effect"] = df["side_effect"].str.title().str.strip()
df["chronic_condition"] = df["chronic_condition"].str.title().str.strip()

print("Strings limpiados y estandarizados.")

"""### 6.5 Manejo de nulos"""

print("Nulos antes:")
print(df.isnull().sum())
print()

# Imputar numericos con mediana
df["age"] = df["age"].fillna(df["age"].median()).astype(int)
df["dosage_mg"] = df["dosage_mg"].fillna(df["dosage_mg"].median()).astype(int)
df["recovery_days"] = df["recovery_days"].fillna(df["recovery_days"].median())

# Imputar categoricos con moda
for col in ["chronic_condition", "alcohol_use"]:
    df[col] = df[col].fillna(df[col].mode()[0])

# Eliminar filas con fechas nulas
df.dropna(subset=["report_date", "treatment_start_date"], inplace=True)
df.reset_index(drop=True, inplace=True)

print("Nulos despues:")
print(df.isnull().sum())
print(f"\nShape final: {df.shape}")

"""## 7. Analisis Exploratorio (EDA)"""

# Distribucion de severidad (target)
print("Distribucion de severidad:")
print(df["severity"].value_counts())
print()
print("Distribucion de outcome:")
print(df["outcome"].value_counts())
print()
print("Distribucion de hospitalized:")
print(df["hospitalized"].value_counts())

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
df["severity"].value_counts().plot(kind="bar", ax=axes[0], title="Severidad")
df["outcome"].value_counts().plot(kind="bar", ax=axes[1], title="Outcome")
df["hospitalized"].value_counts().plot(kind="bar", ax=axes[2], title="Hospitalizado")
plt.tight_layout()
plt.show()

# Distribucion de edad por severidad
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
sns.boxplot(x="severity", y="age", data=df)
plt.title("Edad por severidad")
plt.subplot(1, 2, 2)
sns.boxplot(x="severity", y="dosage_mg", data=df)
plt.title("Dosis por severidad")
plt.tight_layout()
plt.show()

# Variables categoricas vs severidad
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
cat_cols = ["gender", "smoker", "chronic_condition", "alcohol_use", "country", "drug_name"]
for ax, col in zip(axes.flatten(), cat_cols):
    crosstab = pd.crosstab(df[col], df["severity"], normalize="index")
    crosstab.plot(kind="bar", stacked=True, ax=ax, legend=False)
    ax.set_title(f"Severidad por {col}")
    ax.tick_params(axis="x", rotation=45)
plt.tight_layout()
plt.show()

"""## 8. Clasificacion: Prediccion de Severidad

Objetivo: predecir la severidad del efecto secundario (Mild/Moderate/Severe) usando variables del paciente y del farmaco.

### 8.1 Separacion de variables (X, y)
"""

# Target: severity
y = df["severity"]

# Features: excluir side_effect (data leakage - el efecto es consecuencia del target)
feature_cols = ["age", "gender", "country", "drug_name", "dosage_mg",
               "chronic_condition", "smoker", "alcohol_use"]
X = df[feature_cols].copy()

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")
print(f"\nClases: {y.value_counts().to_dict()}")
X.head()

# Codificar target
le = LabelEncoder()
y_encoded = le.fit_transform(y)  # 0=Mild, 1=Moderate, 2=Severe
print(f"Clases codificadas: {dict(zip(le.classes_, range(len(le.classes_))))}")

"""### 8.2 Codificacion de variables categoricas"""

X_encoded = pd.get_dummies(X, columns=["gender", "country", "drug_name",
                                       "chronic_condition",
                                       "smoker", "alcohol_use"],
                          drop_first=True)
print(f"X despues de one-hot: {X_encoded.shape}")
print(f"Columnas: {list(X_encoded.columns[:10])}...")

"""### 8.3 Division train/test"""

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)
print(f"Train: {X_train.shape}, Test: {X_test.shape}")
print(f"Train distribution: {np.bincount(y_train)}")
print(f"Test distribution: {np.bincount(y_test)}")

"""### 8.4 Escalado de datos"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"X_train_scaled: media ~{X_train_scaled.mean():.2f}, std ~{X_train_scaled.std():.2f}")
print(f"X_test_scaled: media ~{X_test_scaled.mean():.2f}, std ~{X_test_scaled.std():.2f}")

"""### 8.5 Entrenamiento de modelos

Probamos 4 algoritmos de clasificacion diferentes:
"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced'),
    "Decision Tree": DecisionTreeClassifier(random_state=42, class_weight='balanced'),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced'),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100, random_state=42),
}

results = {}
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average="weighted")
    results[name] = {"accuracy": acc, "f1_score": f1, "model": model}
    print(f"{name:25s} -> Accuracy: {acc:.4f}, F1: {f1:.4f}")

"""### 8.6 Evaluacion y seleccion del mejor modelo"""

# Mostrar resultados
results_df = pd.DataFrame([
    {"Modelo": name, "Accuracy": v["accuracy"], "F1 Score": v["f1_score"]}
    for name, v in results.items()
])
print(results_df.to_string(index=False))
print()

# Seleccionar el mejor
best_name = max(results, key=lambda k: results[k]["f1_score"])
best_model = results[best_name]["model"]
print(f"MEJOR MODELO: {best_name}")
print()

# Reporte detallado del mejor modelo
y_pred_best = best_model.predict(X_test_scaled)
print("Classification Report:")
print(classification_report(y_test, y_pred_best, target_names=le.classes_))

# Matriz de confusion
cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title(f"Matriz de confusion - {best_name}")
plt.ylabel("Real")
plt.xlabel("Predicho")
plt.show()

"""### 8.7 Predicciones con nuevos datos"""

# Ejemplo: predecir severidad para un paciente nuevo
nuevo_paciente = pd.DataFrame([{
    "age": 55,
    "gender": "Male",
    "country": "USA",
    "drug_name": "Atorvastatin",
    "dosage_mg": 25,
    "chronic_condition": "Hypertension",
    "smoker": "Yes",
    "alcohol_use": "Occasional",
}])

# Aplicar mismo preprocessing
nuevo_encoded = pd.get_dummies(nuevo_paciente, columns=[
    "gender", "country", "drug_name",
    "chronic_condition", "smoker", "alcohol_use"
], drop_first=True)

# Alinear columnas con X_encoded
nuevo_encoded = nuevo_encoded.reindex(columns=X_encoded.columns, fill_value=0)
nuevo_scaled = scaler.transform(nuevo_encoded)

# Predecir
pred = best_model.predict(nuevo_scaled)
proba = best_model.predict_proba(nuevo_scaled)

print(f"Prediccion: {le.inverse_transform(pred)[0]}")
print(f"Probabilidades:")
for clase, prob in zip(le.classes_, proba[0]):
    print(f"  {clase}: {prob:.2%}")

"""### 8.8 Clasificador con Transformer (DistilBERT)

A diferencia de los modelos tradicionales que usan features tabulares, un transformer
procesa el texto directamente. Creamos una descripcion textual de cada caso y
entrenamos DistilBERT para clasificar la severidad.
"""

from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification, Trainer, TrainingArguments

# Crear texto descriptivo de cada fila
def row_to_text_clf(row):
    return f"{row['age']} anios {row['gender']} de {row['country']}. " \
           f"Tomo {row['drug_name']} ({row['dosage_mg']} mg) por {row['chronic_condition']}. " \
           f"Fumador: {row['smoker']}. Alcohol: {row['alcohol_use']}. " \
           f"Efecto: {row['side_effect']}."

texts_clf = df.apply(row_to_text_clf, axis=1).tolist()
labels_clf = y_encoded  # 0=Mild, 1=Moderate, 2=Severe

print(f"Total textos: {len(texts_clf)}")
print(f"Ejemplo:\n{texts_clf[0]}")
print(f"Label: {labels_clf[0]} ({le.classes_[labels_clf[0]]})")

# Tokenizar
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

train_texts, test_texts, train_labels, test_labels = train_test_split(
    texts_clf, labels_clf, test_size=0.2, random_state=42, stratify=labels_clf
)

train_enc = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
test_enc = tokenizer(test_texts, truncation=True, padding=True, max_length=128)

class DrugDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)

train_dataset = DrugDataset(train_enc, train_labels)
test_dataset = DrugDataset(test_enc, test_labels)

print(f"Train: {len(train_dataset)}, Test: {len(test_dataset)}")

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=3
)

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=50,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=lambda eval_pred: {
        "accuracy": (eval_pred.predictions.argmax(-1) == eval_pred.label_ids).mean(),
        "f1": f1_score(eval_pred.label_ids, eval_pred.predictions.argmax(-1), average="weighted"),
    },
)

trainer.train()

print("=== TRANSFORMER (DistilBERT) ===")
eval_result = trainer.evaluate()
print(f"  Accuracy: {eval_result['eval_accuracy']:.4f}")
print(f"  F1 Score: {eval_result['eval_f1']:.4f}")
print()
print("Comparacion con mejor modelo tradicional:")
print(f"  {best_name}: F1={results[best_name]['f1_score']:.4f}")
print(f"  DistilBERT: F1={eval_result['eval_f1']:.4f}")
